# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import unary_pb2 as unary__pb2


class UnaryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerResponseCreateUser = channel.unary_unary(
                '/unary.Unary/GetServerResponseCreateUser',
                request_serializer=unary__pb2.CreateUser.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseLoginUser = channel.unary_unary(
                '/unary.Unary/GetServerResponseLoginUser',
                request_serializer=unary__pb2.Login.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseUpdateUser = channel.unary_unary(
                '/unary.Unary/GetServerResponseUpdateUser',
                request_serializer=unary__pb2.UpdateUser.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseRecoverUser = channel.unary_unary(
                '/unary.Unary/GetServerResponseRecoverUser',
                request_serializer=unary__pb2.UserCID.SerializeToString,
                response_deserializer=unary__pb2.User.FromString,
                )
        self.GetServerResponseRemoveUser = channel.unary_unary(
                '/unary.Unary/GetServerResponseRemoveUser',
                request_serializer=unary__pb2.UserCID.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseGetUser = channel.unary_unary(
                '/unary.Unary/GetServerResponseGetUser',
                request_serializer=unary__pb2.UserCID.SerializeToString,
                response_deserializer=unary__pb2.GetUser.FromString,
                )
        self.GetServerResponseProduct = channel.unary_unary(
                '/unary.Unary/GetServerResponseProduct',
                request_serializer=unary__pb2.ProductPID.SerializeToString,
                response_deserializer=unary__pb2.Product.FromString,
                )
        self.GetServerResponseCreateProduct = channel.unary_unary(
                '/unary.Unary/GetServerResponseCreateProduct',
                request_serializer=unary__pb2.CreateProduct.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseUpdateProduct = channel.unary_unary(
                '/unary.Unary/GetServerResponseUpdateProduct',
                request_serializer=unary__pb2.UpdateProduct.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseListProducts = channel.unary_unary(
                '/unary.Unary/GetServerResponseListProducts',
                request_serializer=unary__pb2.UserCID.SerializeToString,
                response_deserializer=unary__pb2.ArrayProducts.FromString,
                )
        self.GetServerResponseRecoverProduct = channel.unary_unary(
                '/unary.Unary/GetServerResponseRecoverProduct',
                request_serializer=unary__pb2.ProductPID.SerializeToString,
                response_deserializer=unary__pb2.Product.FromString,
                )
        self.GetServerResponseRemoveProduct = channel.unary_unary(
                '/unary.Unary/GetServerResponseRemoveProduct',
                request_serializer=unary__pb2.RemoveProduct.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseCreateOrder = channel.unary_unary(
                '/unary.Unary/GetServerResponseCreateOrder',
                request_serializer=unary__pb2.CreateOrder.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseUpdateOrder = channel.unary_unary(
                '/unary.Unary/GetServerResponseUpdateOrder',
                request_serializer=unary__pb2.UpdateOrder.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )
        self.GetServerResponseListOrder = channel.unary_unary(
                '/unary.Unary/GetServerResponseListOrder',
                request_serializer=unary__pb2.ListOrder.SerializeToString,
                response_deserializer=unary__pb2.Order.FromString,
                )
        self.GetServerResponseListOrderes = channel.unary_unary(
                '/unary.Unary/GetServerResponseListOrderes',
                request_serializer=unary__pb2.UserCID.SerializeToString,
                response_deserializer=unary__pb2.ResultListOrderes.FromString,
                )
        self.GetServerResponseCancelOrder = channel.unary_unary(
                '/unary.Unary/GetServerResponseCancelOrder',
                request_serializer=unary__pb2.CancelOrder.SerializeToString,
                response_deserializer=unary__pb2.Ok.FromString,
                )


class UnaryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServerResponseCreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseLoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseUpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseRecoverUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseRemoveUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseGetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseCreateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseUpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseRecoverProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseRemoveProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseCreateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseUpdateOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseListOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseListOrderes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerResponseCancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnaryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerResponseCreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseCreateUser,
                    request_deserializer=unary__pb2.CreateUser.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseLoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseLoginUser,
                    request_deserializer=unary__pb2.Login.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseUpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseUpdateUser,
                    request_deserializer=unary__pb2.UpdateUser.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseRecoverUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseRecoverUser,
                    request_deserializer=unary__pb2.UserCID.FromString,
                    response_serializer=unary__pb2.User.SerializeToString,
            ),
            'GetServerResponseRemoveUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseRemoveUser,
                    request_deserializer=unary__pb2.UserCID.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseGetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseGetUser,
                    request_deserializer=unary__pb2.UserCID.FromString,
                    response_serializer=unary__pb2.GetUser.SerializeToString,
            ),
            'GetServerResponseProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseProduct,
                    request_deserializer=unary__pb2.ProductPID.FromString,
                    response_serializer=unary__pb2.Product.SerializeToString,
            ),
            'GetServerResponseCreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseCreateProduct,
                    request_deserializer=unary__pb2.CreateProduct.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseUpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseUpdateProduct,
                    request_deserializer=unary__pb2.UpdateProduct.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseListProducts,
                    request_deserializer=unary__pb2.UserCID.FromString,
                    response_serializer=unary__pb2.ArrayProducts.SerializeToString,
            ),
            'GetServerResponseRecoverProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseRecoverProduct,
                    request_deserializer=unary__pb2.ProductPID.FromString,
                    response_serializer=unary__pb2.Product.SerializeToString,
            ),
            'GetServerResponseRemoveProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseRemoveProduct,
                    request_deserializer=unary__pb2.RemoveProduct.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseCreateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseCreateOrder,
                    request_deserializer=unary__pb2.CreateOrder.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseUpdateOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseUpdateOrder,
                    request_deserializer=unary__pb2.UpdateOrder.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
            'GetServerResponseListOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseListOrder,
                    request_deserializer=unary__pb2.ListOrder.FromString,
                    response_serializer=unary__pb2.Order.SerializeToString,
            ),
            'GetServerResponseListOrderes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseListOrderes,
                    request_deserializer=unary__pb2.UserCID.FromString,
                    response_serializer=unary__pb2.ResultListOrderes.SerializeToString,
            ),
            'GetServerResponseCancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerResponseCancelOrder,
                    request_deserializer=unary__pb2.CancelOrder.FromString,
                    response_serializer=unary__pb2.Ok.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Unary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Unary(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServerResponseCreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseCreateUser',
            unary__pb2.CreateUser.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseLoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseLoginUser',
            unary__pb2.Login.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseUpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseUpdateUser',
            unary__pb2.UpdateUser.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseRecoverUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseRecoverUser',
            unary__pb2.UserCID.SerializeToString,
            unary__pb2.User.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseRemoveUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseRemoveUser',
            unary__pb2.UserCID.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseGetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseGetUser',
            unary__pb2.UserCID.SerializeToString,
            unary__pb2.GetUser.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseProduct',
            unary__pb2.ProductPID.SerializeToString,
            unary__pb2.Product.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseCreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseCreateProduct',
            unary__pb2.CreateProduct.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseUpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseUpdateProduct',
            unary__pb2.UpdateProduct.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseListProducts',
            unary__pb2.UserCID.SerializeToString,
            unary__pb2.ArrayProducts.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseRecoverProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseRecoverProduct',
            unary__pb2.ProductPID.SerializeToString,
            unary__pb2.Product.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseRemoveProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseRemoveProduct',
            unary__pb2.RemoveProduct.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseCreateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseCreateOrder',
            unary__pb2.CreateOrder.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseUpdateOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseUpdateOrder',
            unary__pb2.UpdateOrder.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseListOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseListOrder',
            unary__pb2.ListOrder.SerializeToString,
            unary__pb2.Order.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseListOrderes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseListOrderes',
            unary__pb2.UserCID.SerializeToString,
            unary__pb2.ResultListOrderes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerResponseCancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Unary/GetServerResponseCancelOrder',
            unary__pb2.CancelOrder.SerializeToString,
            unary__pb2.Ok.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
